### ISSUE TITLE
`Dockerfile` improvements

### ISSUE THREAD

**Issue by yafetn** [AdaptiveConsulting/aeron-io-samples#125]
Hello,

Thanks for putting out these samples and for the documentation.

I wanted to make some changes to the Dockerfiles but thought to open an issue first. The proposed changes are:

1. To not run the containers as `root` but as a separate user (maybe `aeron`)
2. Decrease the repetitiveness of `COPY...` statements by using `.dockerignore` files
3. Replace `wget ....` in favor of `ADD...` commands.

Let me know if these sound reasonable and I'll be happy to open a PR.

**Comment by eleventy7** [comment]
I've made some initial changes around the first point - the applications in the containers no longer run under `root` but now `aeron,` as suggested.
